#서버 설정
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      charset: UTF-8 
      force-response: true
      
#뷰리졸버 설정      
spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp

  messages:
    basename: message/messageSource
    encoding: UTF-8
    fallback-to-system-locale: false
    always-use-message-format: true
      
  #데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    
  #JAP 설정 
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update 
    properties:
      hibernate.format_sql: true
